trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: 'Terraform-Variables'

stages:
  - stage: TerraformValidate
    displayName: 'Terraform Validate'
    jobs:
      - job: InstallandaValidate
        displayName: 'Install Terraform and Validate'
        steps:
          - task: TerraformInstaller@1
            displayName: 'Terraform Install'
            inputs:
              terraformVersion: '$(terraform_version)'

          - task: TerraformTask@5
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: '$(service-connection)'
              backendAzureRmResourceGroupName: 'RG'
              backendAzureRmStorageAccountName: 'tfstatefilestore1678'
              backendAzureRmContainerName: 'tfstate-container'
              backendAzureRmKey: 'terraform.tfstate'
              backendAzureRmSubscriptionId: '$(subscription_id)'
              

          - task: TerraformTask@5
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: TerraformPlan
    displayName: 'Terraform Plan'
    dependsOn: TerraformValidate
    condition: succeeded()
    jobs:
      - job: Plan
        displayName: 'Terraform Plan'
        steps:
          - task: TerraformInstaller@1
            displayName: 'Terraform Install'
            inputs:
              terraformVersion: '$(terraform_version)'

          - task: TerraformTask@5
            displayName: 'Terraform Init (Plan Stage)'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: '$(service-connection)'
              backendAzureRmResourceGroupName: 'RG'
              backendAzureRmStorageAccountName: 'tfstatefilestore1678'
              backendAzureRmContainerName: 'tfstate-container'
              backendAzureRmKey: 'terraform.tfstate'
              backendAzureRmSubscriptionId: '$(subscription_id)'
              

          - task: TerraformTask@5
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: '$(service-connection)'

  - stage: TerraformApply
    displayName: 'Terraform Apply'
    dependsOn: TerraformPlan
    condition: succeeded()
    jobs:
      - job: Apply
        displayName: 'Terraform Apply'
        steps:
          - task: TerraformInstaller@1
            displayName: 'Terraform Install'
            inputs:
              terraformVersion: '$(terraform_version)'

          - task: TerraformTask@5
            displayName: 'Terraform Init (Apply Stage)'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: '$(service-connection)'
              backendAzureRmResourceGroupName: 'RG'
              backendAzureRmStorageAccountName: 'tfstatefilestore1678'
              backendAzureRmContainerName: 'tfstate-container'
              backendAzureRmKey: 'terraform.tfstate'
              backendAzureRmSubscriptionId: '$(subscription_id)'
              

          - task: TerraformTask@5
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: '$(service-connection)'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
