package_update: true
package_upgrade: true

packages:
  - docker.io
  - curl

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - docker pull sreenija4363/nginx-image:latest
  - docker run -d -p 80:80 --name webserver sreenija4363/nginx-image:latest